global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-jmx-exporter'
    static_configs:
      - targets: ['kafka-1:7071', 'kafka-2:7072', 'kafka-3:7073']

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka-1:9001', 'kafka-2:9002', 'kafka-3:9003']